### ISSUE TITLE
Docker restart always

### ISSUE THREAD

**Issue by Fr33loader** [tom472/mediabox#45]
Hi guys,

Just a small question that has left me puzzled.

**Problem**

The default docker image setup does not really suit my needs, since I would prefer that if I did a reboot of my server, my docker containers would automatically reboot.

To that end, I added a "restart: always" in my docker-compose file.

Example:

```
arch-delugevpn:
        image: ledokun/armhf-arch-delugevpn
        container_name: delugevpn
        restart: always
        network_mode: "bridge"
```

Unfortunately, no luck. On force reboot, it exits the docker container and does not reboot. Anything I'm missing?
