### ISSUE TITLE
Update docker-compose version

### ISSUE THREAD

**Issue by trevor-e** [tom472/mediabox#46]
Currently `docker-compose.yml` is set to `version: '2'` which I believe is fairly out of date. On my local setup I'm using an NFS volume for some images which requires features available in version 3.x+. Eg:

```
volumes:
    nfsMount:
        driver: local
        driver_opts:
            type: nfs
            o: addr=192.168.1.23
            device: ":/nfs/Public"
```

Everything appears to work fine after setting `version: 3.5` and would be nice to have upstream too. Thanks for the great project!
